### ISSUE TITLE
Error logged to dev tools in VS Code

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/tas-client#9]
Hello 👋  in VS Code we've been seeing:

> (node:88228) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/tyleonha/Code/Microsoft/vscode/extensions/github-authentication/node_modules/vscode-tas-client/package.json' of './out/index'. Please either fix that or report it to the module author(Use `Electron --trace-deprecation ...` to show where the warning was created)

and one for `tas-client` as well. This seems to be because of this:
https://nodejs.org/api/deprecations.html#DEP0128

and the reason is that your main set to `./out/index` is invalid and should be just `index.js` based on the package contents:
![image](https://user-images.githubusercontent.com/2644648/154580248-1d38c196-52ff-4a90-9b5b-79981ddaefa9.png)

or on the flip side, update the build script to keep the `out` folder? which I'm guessing is happening here:
https://github.com/microsoft/tas-client/blob/main/vscode-tas-client/gulpfile.js#L69

**Comment by daytonellwanger** [comment]
@TylerLeonhardt , just wanted to confirm that this issue is fixed on the latest version of the package?

**Comment by TylerLeonhardt** [comment]
Yep! I'm no longer seeing these.
